-- Crie o usuário admin pelo dashboard do Supabase (Authentication → Add user)
-- com uma senha forte. O trigger on_auth_user_created cria o profile com
-- role 'viewer'; promova a admin manualmente:
--   UPDATE public.profiles SET role = 'admin' WHERE id = '<uuid-do-usuario>';
-- Nunca versione email/senha reais neste arquivo.
